### ISSUE TITLE
File txt

### ISSUE THREAD

**Issue by vornao** [lilf4p/hlt-homework#1]
ciao capo apro un issue solo per romperti le scatole 

i file txt che hai generato sono obbligatori per la consegna o li hai fatti per averli?

ciao

Luca

**Comment by lilf4p** [comment]
ciao
dopo un ora dalla scadenza
li ho fatti solo per me 
output troppo grande per il notebook e volevo leggerlo tutto
comunque si puo' consegnare anche in ritardo 
ciao 
Leonardo

**Comment by vornao** [comment]
ok bene grazie Leonardo per le informazioni.
